obj-m += driver_spi_sh1106.o
 
KDIR = /lib/modules/$(shell uname -r)/build
 
 
all:
	make -C $(KDIR)  M=$(shell pwd) modules
 
clean:
	make -C $(KDIR)  M=$(shell pwd) clean
reinstall:
	sudo rmmod driver_spi_sh1106
	make clean
	make
	sudo insmod driver_spi_sh1106.ko